// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaberOnline.Aluno.Data.Context;

#nullable disable

namespace SaberOnline.Aluno.Data.Migrations
{
    [DbContext(typeof(AlunoDbContext))]
    [Migration("20251012214826_Aluno")]
    partial class Aluno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("SaberOnline.Aluno.Domain.Entities.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("AlunoId");

                    b.Property<Guid>("CodigoUsuarioAutenticacao")
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("CodigoUsuarioAutenticacao");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("SmallDateTime")
                        .HasColumnName("DataNascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar")
                        .HasColumnName("Email")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar")
                        .HasColumnName("Nome")
                        .UseCollation("Latin1_General_CI_AI");

                    b.HasKey("Id")
                        .HasName("AlunosPK");

                    b.ToTable("Alunos", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
