// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaberOnline.Aluno.Data.Context;

#nullable disable

namespace SaberOnline.Aluno.Data.Migrations
{
    [DbContext(typeof(AlunoDbContext))]
    [Migration("20251111200514_AlunoMigration")]
    partial class AlunoMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("SaberOnline.Aluno.Domain.Entities.Aluno", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("AlunoId");

                    b.Property<Guid>("CodigoUsuarioAutenticacao")
                        .HasColumnType("UniqueIdentifier")
                        .HasColumnName("CodigoUsuarioAutenticacao");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("SmallDateTime")
                        .HasColumnName("DataNascimento");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("Varchar")
                        .HasColumnName("Email")
                        .UseCollation("Latin1_General_CI_AI");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("Varchar")
                        .HasColumnName("Nome")
                        .UseCollation("Latin1_General_CI_AI");

                    b.HasKey("Id")
                        .HasName("AlunosPK");

                    b.ToTable("Alunos", (string)null);
                });

            modelBuilder.Entity("SaberOnline.Aluno.Domain.Entities.Certificado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatriculaCursoId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PathCertificado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaCursoId")
                        .IsUnique();

                    b.ToTable("Certificados");
                });

            modelBuilder.Entity("SaberOnline.Aluno.Domain.Entities.MatriculaCurso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("UniqueIdentifier");

                    b.Property<Guid>("CursoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataMatricula")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstadoMatricula")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeCurso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId");

                    b.ToTable("MatriculasCursos");
                });

            modelBuilder.Entity("SaberOnline.Aluno.Domain.ValueObjects.HistoricoAprendizado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatriculaCursoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MatriculaCursoId");

                    b.ToTable("HistoricoAprendizado");
                });

            modelBuilder.Entity("SaberOnline.Aluno.Domain.Entities.Certificado", b =>
                {
                    b.HasOne("SaberOnline.Aluno.Domain.Entities.MatriculaCurso", "MatriculaCurso")
                        .WithOne("Certificado")
                        .HasForeignKey("SaberOnline.Aluno.Domain.Entities.Certificado", "MatriculaCursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatriculaCurso");
                });

            modelBuilder.Entity("SaberOnline.Aluno.Domain.Entities.MatriculaCurso", b =>
                {
                    b.HasOne("SaberOnline.Aluno.Domain.Entities.Aluno", "Aluno")
                        .WithMany("MatriculasCursos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });

            modelBuilder.Entity("SaberOnline.Aluno.Domain.ValueObjects.HistoricoAprendizado", b =>
                {
                    b.HasOne("SaberOnline.Aluno.Domain.Entities.MatriculaCurso", null)
                        .WithMany("HistoricoAprendizado")
                        .HasForeignKey("MatriculaCursoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SaberOnline.Aluno.Domain.Entities.Aluno", b =>
                {
                    b.Navigation("MatriculasCursos");
                });

            modelBuilder.Entity("SaberOnline.Aluno.Domain.Entities.MatriculaCurso", b =>
                {
                    b.Navigation("Certificado")
                        .IsRequired();

                    b.Navigation("HistoricoAprendizado");
                });
#pragma warning restore 612, 618
        }
    }
}
